### ISSUE TITLE
vite related module not found when open http://localhost:3003/open-source

### ISSUE THREAD

**Issue by cloudslsw** [nkzw-tech/athena-crisis#46]
PS E:\Documents\source\athena-crisis> pnpm dev

> @deities/athena-crisis@0.0.2 dev E:\Documents\source\athena-crisis
> cd docs && pnpm dev

> @deities/docs@0.0.1 dev E:\Documents\source\athena-crisis\docs
> vocs dev --port 3003

21:44:32 [vite] building search index...

  [running] vocs@v1.0.0-alpha.51

  ➜  Local:   http://localhost:3003/open-source
  ➜  Network: use --host to expose
21:44:34 [vite] Pre-transform error: Failed to load url /@fsE:\Documents\source\athena-crisis\node_modules\.pnpm\vocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq\node_modules\vocs\_lib\app/index.client.js (resolved id: /@fsE:\Documents\source\athena-crisis\node_modules\.pnpm\vocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq\node_modules\vocs\_lib\app/index.client.js). Does the file exist?
21:44:35 [vite] Pre-transform error: Failed to load url E:Documentssourceathena-crisis
ode_modules.pnpm
ocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq
ode_modules
ocs_lib
ite.vocs        heme.css (resolved id: E:Documentssourceathena-crisis
ode_modules.pnpm
ocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq
ode_modules
ocs_lib
ite.vocs        heme.css) in virtual:styles. Does the file exist?
21:44:35 [vite] Pre-transform error: Failed to load url E:Documentssourceathena-crisisdocscontentstyles.css (resolved id: E:Documentssourceathena-crisisdocscontentstyles.css) in virtual:styles. Does the file exist?
21:44:38 [vite] Error when evaluating SSR module virtual:styles: failed to import "E:Documentssourceathena-crisis
ode_modules.pnpm
ocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq
ode_modules
ocs_lib
ite.vocs        heme.css"
|- Error: Cannot find module 'E:Documentssourceathena-crisis
ode_modules.pnpm
ocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq
ode_modules
ocs_lib
ite.vocs        heme.css' imported from 'virtual:styles'
    at nodeImport (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56268:25)
    at ssrImport (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56177:30)
    at eval (virtual:styles:3:50)
    at instantiateModule (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56237:15)

21:44:38 [vite] Error when evaluating SSR module /@fs/E:/Documents/source/athena-crisis/node_modules/.pnpm/vocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq/node_modules/vocs/_lib/app/root.js: failed to import "virtual:styles"
|- Error: Cannot find module 'E:Documentssourceathena-crisis
ode_modules.pnpm
ocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq
ode_modules
ocs_lib
ite.vocs        heme.css' imported from 'virtual:styles'
    at nodeImport (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56268:25)
    at ssrImport (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56177:30)
    at eval (virtual:styles:3:50)
    at instantiateModule (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56237:15)

21:44:38 [vite] Error when evaluating SSR module /@fs/E:/Documents/source/athena-crisis/node_modules/.pnpm/vocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq/node_modules/vocs/_lib/app/routes.js: failed to import "/@fs/E:/Documents/source/athena-crisis/node_modules/.pnpm/vocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq/node_modules/vocs/_lib/app/root.js"
|- Error: Cannot find module 'E:Documentssourceathena-crisis
ode_modules.pnpm
ocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq
ode_modules
ocs_lib
ite.vocs        heme.css' imported from 'virtual:styles'
    at nodeImport (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56268:25)
    at ssrImport (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56177:30)
    at eval (virtual:styles:3:50)
    at instantiateModule (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56237:15)

21:44:38 [vite] Error when evaluating SSR module E:\Documents\source\athena-crisis\node_modules\.pnpm\vocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq\node_modules\vocs\_lib\app\index.server.js: failed to import "/@fs/E:/Documents/source/athena-crisis/node_modules/.pnpm/vocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq/node_modules/vocs/_lib/app/routes.js"
|- Error: Cannot find module 'E:Documentssourceathena-crisis
ode_modules.pnpm
ocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq
ode_modules
ocs_lib
ite.vocs        heme.css' imported from 'virtual:styles'
    at nodeImport (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56268:25)
    at ssrImport (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56177:30)
    at eval (virtual:styles:3:50)
    at instantiateModule (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56237:15)

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Cannot find module 'E:Documentssourceathena-crisis
ode_modules.pnpm
ocs@1.0.0-alpha.52_@types+node@20.14.2_@types+react-dom@18.3.0_@types+react@18.3.3_babel-plu_4v4obqvrv26uvzezrtpkgcatzq
ode_modules
ocs_lib
ite.vocs        heme.css' imported from 'virtual:styles'
    at nodeImport (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56268:25)
    at ssrImport (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56177:30)
    at eval (virtual:styles:3:50)
    at instantiateModule (file:///E:/Documents/source/athena-crisis/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56237:15) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.14.0
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by cpojer** [comment]
The issue is related to Vocs and we are waiting for a new version, see https://github.com/wevm/vocs/issues/52

I recommend using WSL on Windows to get the docs site to work.

**Comment by cloudslsw** [comment]
thanks, got it, i used to regard it as a dedicated server for this game,  i start to realize this is just a website after saw your reply XD

**Comment by cpojer** [comment]
Check out this blog post for more information about what is and isn't open source: https://cpojer.net/posts/athena-crisis-open-source
